stages:
  - compile
  - container

build_code:
  stage: compile
  image: golang:1.24.6
  tags:
    - cloud
  script:
    - go build -o build/dockman-exporter src/dockman-exporter.go
  artifacts:
    paths:
      - build/dockman-exporter
    expire_in: 1h

build_container:
  stage: container
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  image: quay.io/buildah/stable
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  tags:
    - podman
  script:
    - buildah build -t $IMAGE_TAG .
    - buildah push $IMAGE_TAG
  dependencies:
    - build_code
